info:
  component: Config Server (Remote Properties)
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mouserd/config-repo

server:
  port: 8888
